<?php

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var  Magepow\Featured\Block\Display $block
 */
?>
<?php

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
<?php
if ($block->getMode() == 'grid') {
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
    $viewMode = 'list';
    $image = 'category_page_list';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}

/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
$position = '';
if ($pos != null) {
    $position = ' style="left:' . $block->getVar("{$image}:width") . 'px;'
        . 'top:' . $block->getVar("{$image}:height") . 'px;"';
}
?>
    <div class="e-commerce-product">
        <div class="container">
            <div class="row">
                <?php /** @var $_product Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                <div class="col-md-2">
                        <div class="content">
                            <?php
                            $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                ->init($_product, 'product_page_image_large')
                                ->keepAspectRatio(TRUE)
                                ->keepFrame(FALSE)
                                ->resize(270, 371)
                                ->getUrl();
                            ?>
                            <img src="<?php echo $imageUrl; ?>" alt="image">
                            <div class="product-btn">
                                <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <span><?php echo __('Add to Compare') ?></span>
                                        </a>
                                    </div>
                                </div>
    <!--                            <a href="#">Add To Cart</a>-->
    <!--                            <span>-->
    <!--                                        <a href="#"><i class="fa fa-shopping-cart"></i></a>-->
    <!--                                        <a href="#"><i class="fa fa-heart-o"></i></a>-->
    <!--                                    </span>-->
                            </div>
                        </div>
                        <div class="product-details">
                            <h4 class="title">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php echo $_product->getProductUrl() ?>">
                                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                            </h4>
                            <div class="price"><ins><?php echo $block->getProductPrice($_product) ?></ins></div>
                        </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>

<script text="text/javascript">
    require([
        'jquery',
        'slick'
    ], function($ , slick){
        $('.row').slick({
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 3,
            autoplay: true,
            autoplaySpeed: 2000
        });
    });
</script>

